// api/_config/plans.js
// AUTO-GENERATED by batch-runner/forge-create-plans.js
// DO NOT EDIT MANUALLY — run the script to regenerate
// Last generated: 2026-06-23T08:00:00Z

const PLANS = {
  sandbox: {
    product_id: 'PROD-placeholder-testing',
    t1: { plan_id: 'I-placeholder-t1', price: 99,  label: 'Local SEO Maintenance Engine',  monthly_label: '£99/mo'  },
    t2: { plan_id: 'I-placeholder-t2', price: 249, label: 'Hyper-Local Dominator',         monthly_label: '£249/mo' },
    t3: { plan_id: 'I-placeholder-t3', price: 499, label: 'Total Agentic Dominance',       monthly_label: '£499/mo' }
  },
  live: {
    product_id: null,
    t1: { plan_id: null, price: 99,  label: 'Local SEO Maintenance Engine',  monthly_label: '£99/mo'  },
    t2: { plan_id: null, price: 249, label: 'Hyper-Local Dominator',         monthly_label: '£249/mo' },
    t3: { plan_id: null, price: 499, label: 'Total Agentic Dominance',       monthly_label: '£499/mo' }
  }
}

export function getActivePlans() {
  const mode = process.env.PAYPAL_MODE === 'live' ? 'live' : 'sandbox'
  return PLANS[mode]
}

export { PLANS }